#!/usr/bin/env python3
"""Interaktiver CLI-Tracker für Arbeitszeiten."""

from whtracker import (
    COMMAND_ALIASES,
    HELP_TEXT,
    PAUSE_REMINDER_MINUTES,
    REMINDER_TIMEOUT_SECONDS,
    MacReminderUI,
    Pause,
    ParseError,
    ReminderUI,
    State,
    Tracker,
    AbsenceEntry,
    WorkDay,
    backup_existing,
    berlin_holidays,
    format_duration_de,
    format_end_time,
    format_hours,
    generate_pdf,
    load_hours_payload,
    main,
    normalize_command,
    parse_add_pause_entry,
    parse_clock_adjust_entry,
    parse_edit_entry,
    parse_hours_query,
    parse_manual_entry,
    parse_start_clock,
    parse_absence_entry,
    pause_full_minutes,
    reminder_window_open,
    round_to_quarter_hours,
    run_cli,
    target_breakdown,
    target_hours,
)

__all__ = [
    "COMMAND_ALIASES",
    "HELP_TEXT",
    "PAUSE_REMINDER_MINUTES",
    "REMINDER_TIMEOUT_SECONDS",
    "MacReminderUI",
    "Pause",
    "ParseError",
    "ReminderUI",
    "State",
    "Tracker",
    "AbsenceEntry",
    "WorkDay",
    "backup_existing",
    "berlin_holidays",
    "format_duration_de",
    "format_end_time",
    "format_hours",
    "generate_pdf",
    "load_hours_payload",
    "main",
    "normalize_command",
    "parse_add_pause_entry",
    "parse_clock_adjust_entry",
    "parse_edit_entry",
    "parse_hours_query",
    "parse_manual_entry",
    "parse_start_clock",
    "parse_absence_entry",
    "pause_full_minutes",
    "reminder_window_open",
    "round_to_quarter_hours",
    "run_cli",
    "target_breakdown",
    "target_hours",
]

if __name__ == "__main__":
    main()
